### ISSUE TITLE
Mobile app can display graph

### ISSUE THREAD

**Issue by tommyle153** [tommyle153/491A_Project#101]

**Comment by tommyle153** [comment]
can redirect user with 
WebBrowser.openBrowserAsync(
      'http://smartergarden4.me'
problem: graphs is currently only accessible to logged-in users
suggestion: make the graph.php page redirect to login and then back to previous page
after succesful login?

**Comment by lamtran409** [comment]
bootstrap need to be done if we need webview for graph

**Comment by lamtran409** [comment]
Finished the webview for graph. We dont need to redirect users to web browser.
