### ISSUE TITLE
Access to Apple Team ID for developing .ipa for sideload

### ISSUE THREAD

**Issue by tommyle153** [tommyle153/491A_Project#114]

**Comment by tommyle153** [comment]
Solution 1: pay the $99/year fee for Apple and one-time $25 fee for android to put in the market.
Solution 2: Make our app side-load only, and transfer them to people who wishes to use our app via usb cable.
Solution 2.1: Due to needing Apple Team ID # for Expo to create ipa, let classmates download Expo Client to simulate app during demo.

**Comment by lamtran409** [comment]
we can temporary use solution 2. I will pay $99/year for Apple in November
